Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
          # partition key
        - AttributeName: userId
          KeyType: HASH
          # sort key
        - AttributeName: noteId
          KeyType: RANGE
      # Set the capacity to auto-scale
      # using provisioned since it is free-tier elegible
      # BillingMode: PAY_PER_REQUEST
      BillingMode: PROVISIONED
      # If you set BillingMode as PROVISIONED, you must specify this property.
      ProvisionedThroughput:
        # using default values
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  DynamoDBTable:
    Value: !Ref NotesTable